apiVersion: v2
name: litter
version: 0.0.1 # version of Helm chart
appVersion: "{{ .Values.app.metadata.appVersion }}" # version of app image, replaced during CI/CD pipeline
description: A Helm chart for the Litter application on Kubernetes (with Azure AKS)
type: application