# overrides for prod environment
# if no overrides are needed, include an empty object "---" or else yq will error
app:
  replicaCount: 3
  resources:
    requests:
      memory: "512Mi" # double base resources for prod
      cpu: "200m"
      storage: "512Mi"
    limits:
      memory: "1Gi"
      cpu: "1"
      storage: "1Gi"
mongo:
  resources:
    requests:
      memory: "1Gi" # double base resources for prod
      cpu: "200m"
      storage: "512Mi"
    limits:
      memory: "1Gi"
      cpu: "1"
      storage: "2Gi"
