app:
  replicaCount: 2
  metadata:
    labels:
      app: litter-app
      sa: litter-app-sa
      component: app
      secret: litter-secrets
    friendlyAppName: "Litter"
  image:
    tag: ""        # will be overridden
    repository: "" # will be overridden
    pullPolicy: Always
  service:
    port: 8080
    selector: litter-app
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
      storage: "128Mi"
    limits:
      memory: "512Mi"
      cpu: "250m"
      storage: "256Mi"
  env:
    MONGO_HOST: "litter-db"
    MONGO_PORT: "27017"
    MONGO_DB: "" # will be overridden
  secrets:
    mode: k8s-secret                  # set to "key-vault" to use Azure Key Vault, or "k8s-secret" to use k8s secret
    kvClassName: "litter-kv-provider" # Azure Key Vault provider class name (if using Azure Key Vault)
    values:
      db-user-username: ""  # MongoDB username for Litter app
      db-user-password: ""  # MongoDB password for Litter app
      jwt-secret: ""        # JWT secret for Litter app
mongo:
  replicaCount: 1
  metadata:
    labels:
      app: litter-db
      sa: litter-db-sa
      component: db
  image:
    repository: mongo
    tag: "8.0"
  service:
    port: 27017
    selector: litter-db
  volume:
    pvc:
      name: litter-db-pvc
    mountPath: /data/db
    mountName: mongo-data
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
      storage: "256Mi"
    limits:
      memory: "512Mi"
      cpu: "250m"
      storage: "2Gi"
