app:
  replicaCount: 2
  metadata:
    labels:
      app: litter-app
      sa: litter-app-sa
      component: app
    friendlyAppName: "Litter"
  image:
    tag: ""         # replaced during CI/CD pipeline
    repository: ""  # replaced during CI/CD pipeline
    pullPolicy: Always
  service:
    port: 8080
    selector: litter-app
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
      storage: "128Mi"
    limits:
      memory: "512Mi"
      cpu: "250m"
      storage: "256Mi"
  env:
    - name: MONGO_HOST
      value: "{{ .Values.mongo.service.name }}"
    - name: MONGO_PORT
      value: "{{ .Values.mongo.service.port }}"
    - name: MONGO_DB
      value: "{{ .Values.mongo.dbName }}"
    - name: MONGO_USER
      valueFrom:
        secretKeyRef:
          name: litter-secrets
          key: mongo-app-username
    - name: MONGO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: litter-secrets
          key: mongo-app-password
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: litter-secrets
          key: jwt-secret
mongo:
  replicaCount: 1
  metadata:
    labels:
      app: litter-db
      sa: litter-db-sa
      component: db
  image:
    repository: mongo
    tag: "8.0"
  service:
    port: 27017
    selector: litter-db
  dbName: litter
  volume:
    pvc:
      name: litter-db-pvc
    mountPath: /data/db
    mountName: mongo-data
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
      storage: "256Mi"
    limits:
      memory: "512Mi"
      cpu: "250m"
      storage: "2Gi"
