app:
  imagePullSecrets: [ { name: "container-registry-secret" } ]
  replicaCount: 2
  metadata:
    appVersion: ""  # replaced during CI/CD pipeline
    labels:
      app: litter-app
      sa: litter-app-sa
      component: app
    friendlyAppName: "Litter"
  image:
    tag: ""  # replaced during CI/CD pipeline
    repository: ""  # replaced during CI/CD pipeline
    pullPolicy: Always
  service:
    port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
      storage: "256Mi"
    limits:
      memory: "512Mi"
      cpu: "500m"
      storage: "512Mi"
  env:
    - name: MONGODB_URI  # replaced via k8s secret
      valueFrom:
        secretKeyRef:
          name: litter-secrets
          key: mongo-uri
    - name: JWT_SECRET  # replaced via k8s secret
      valueFrom:
        secretKeyRef:
          name: litter-secrets
          key: jwt-secret

mongo:
  replicaCount: 1
  metadata:
    labels:
      app: litter-db
      sa: litter-db-sa
      component: db
  image:
    repository: mongo
    tag: "8.0"
  volume:
    pv:
      name: litter-db-pv
    pvc:
      name: litter-db-pvc
    size: "4Gi"
    mountPath: /data/db
    mountName: mongo-data
    storageClassName: "managed-csi"
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
      storage: "256Mi"
    limits:
      memory: "512Mi"
      cpu: "500m"
      storage: "1Gi"