services:
  litter-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.private/.env
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      # enable remote debugging
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    depends_on:
      - litter-db

  litter-db:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    name: litter-network
    driver: bridge