apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.metadata.labels.app }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mongo.service.selector }}

  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
