{{- if eq .Values.app.secrets.mode "k8s-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.metadata.labels.secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.app.secrets.values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
