apiVersion: v1
kind: Service

metadata:
  name: litter-app
  namespace: {{ .Release.Namespace }}

spec:
  type: NodePort
  selector:
    app: litter-app

  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
