apiVersion: v1
kind: Service

metadata:
  name: litter-db
  namespace: {{ .Release.Namespace }}

spec:
  type: ClusterIP
  selector:
    app: litter-db

  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
