apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.metadata.labels.app }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.service.selector }}

  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}