apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.metadata.labels.app }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongo.metadata.labels.app }}
      component: {{ .Values.mongo.metadata.labels.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.metadata.labels.app }}
        component: {{ .Values.mongo.metadata.labels.component }}
    spec:
      serviceAccountName: {{ .Values.mongo.metadata.labels.sa }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.mongo.metadata.labels.app }}
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: {{ .Values.mongo.resources.requests.memory }}
              cpu: {{ .Values.mongo.resources.requests.cpu }}
              ephemeral-storage: {{ .Values.mongo.resources.requests.storage }}
            limits:
              memory: {{ .Values.mongo.resources.limits.memory }}
              cpu: {{ .Values.mongo.resources.limits.cpu }}
              ephemeral-storage: {{ .Values.mongo.resources.limits.storage }}
          volumeMounts:
            - name: {{ .Values.mongo.volume.mountName }}
              mountPath: {{ .Values.mongo.volume.mountPath }}
      volumes:
        - name: {{ .Values.mongo.volume.mountName }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.volume.pvc.name }}