# only create the PV if the volume is not managed externally
{{- if not .Values.mongo.volume.external }}
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: {{ .Values.mongo.volume.csi.driver }}
  name: {{ .Values.mongo.volume.pv.name }}
  namespace: {{ .Release.Namespace }}

spec:
  capacity:
    storage: {{ .Values.mongo.volume.size }}
  accessModes:
    - ReadWriteOnce
  csi:
    driver: {{ .Values.mongo.volume.csi.driver }}
    volumeHandle: {{ required "VolumeHandle is required" .Values.mongo.volume.csi.volumeHandle }}
    volumeAttributes:
      fsType: {{ .Values.mongo.volume.fsType }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongo.volume.storageClassName }}
{{- end }}