apiVersion: v1
kind: Secret
metadata:
  name: litter-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mongodb-uri: {{ .Values.app.env.mongodbUri | b64enc }}
  jwt-secret: {{ .Values.app.env.jwtSecret | b64enc }}
