# read the secret values from the mounted secrets volume
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:litter}
      username: ${file:/mnt/secrets/db-user-username}
      password: ${file:/mnt/secrets/db-user-password}
jwt:
  secret: ${file:/mnt/secrets/jwt-secret}
  issuer: litter
  expiration-time: 3600000 # 1 hour in milliseconds

server:
  port: 8080
