# read the environment variables to connect to the database
spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:litter}
      username: ${MONGO_USER:}
      password: ${MONGO_PASSWORD:}

# JWT secret is also read from its environment variable
jwt:
  secret: ${JWT_SECRET}
  issuer: litter
  expiration-time: 3600000 # 1 hour in milliseconds

server:
  port: 8080
