---
config:
  theme: dark
  look: handDrawn
  layout: dagre
---
flowchart TB
 subgraph GHA_subgraph["GitHub Actions Workflow"]
        B["Build & Test w/ Gradle"]
        I["Build Image"]
        P["Push to Registry"]
        TP["Terraform Plan"]
        TA["Terraform Apply"]
  end
 subgraph GH_subgraph["GitHub"]
        GHA_subgraph
        GHCR["GHCR"]
  end
 subgraph DNS_subgraph["DNS Resource Group"]
        DNS["Azure DNS Zone"]
  end
 subgraph KV_subgraph["Key Vault Resource Group"]
        KV["Key Vault"]
  end
 subgraph in_subgraph["Ingress & TLS"]
        ING["NGINX Ingress"]
        ACME["Cert Manager"]
  end
 subgraph app_subgraph["Application Tier"]
        APP1["Litter App Pod 1"]
        APP2["Litter App Pod 2, etc."]
  end
 subgraph db_subgraph["Database Tier"]
        MDB["MongoDB Pod"]
        PV["Persistent Volume"]
        CAT@{ img: "https://openclipart.org/download/321312/catinlitterbox.svg", h: 100, w: 100, pos: "b"}

  end
 subgraph res_subgraph["Kubernetes Resources"]
        SEC["K8s Secrets"]
        SVC["LoadBalancer Service"]
        app_subgraph
        db_subgraph
  end
 subgraph aks_subgraph["Azure Kubernetes Service"]
        in_subgraph
        res_subgraph
  end
 subgraph aks_rg_subgraph["AKS Resource Group"]
        aks_subgraph
  end
 subgraph az_subgraph["Azure Cloud"]
        DNS_subgraph
        KV_subgraph
        aks_rg_subgraph
  end
    B --> P
    P --> TP
    TP --> TA
    DR["Domain Registrar"] -- assign nameserver --> DNS
    P -- push image --> GHCR
    TA -- deploy infrastructure --> AKS["AKS"]
    DNS -- DNS records --> ING
    KV -- secrets source --> SEC
    SEC -- mount secrets --> APP1 & APP2 & MDB
    ING -- route traffic --> SVC
    ACME -- TLS certs --> ING
    SVC -- load balance --> APP1 & APP2
    APP1 -- read/write --> MDB
    APP2 -- read/write --> MDB
    MDB -- provision/claim --> PV
    MDB -- download brown load --> CAT
     I:::github
     P:::github
     TP:::github
     TA:::github
     GHCR:::github
     DNS:::azure
     KV:::azure
     ING:::k8s
     ACME:::k8s
     APP1:::k8s
     APP2:::k8s
     MDB:::k8s
     PV:::k8s
     SEC:::k8s
     SVC:::k8s
     DR:::external
    classDef azure fill:#0072C6,color:white,stroke:white
    classDef k8s fill:#326CE5,color:white,stroke:white
    classDef github fill:#24292E,color:white,stroke:white
    classDef external fill:#cccccc,color:black,stroke:black
