services:
  litter-app:
    image: ghcr.io/mchar7/litter:latest # adjust to your registry/image
    env_file:
      - .env # your edited example.env
    ports:
      - "8080:8080"
    depends_on:
      - litter-db

  litter-db:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    name: litter-network
    driver: bridge
