services:
  litter-app:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/litter.jar
    env_file:
      - example.env # your edited example.env
    ports:
      - "8080:8080"
      - "5005:5005" # for remote debugging
    depends_on:
      - litter-db

  litter-db:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    name: litter-network
    driver: bridge
