name: Build and Deploy

env:
  AZURE_AKS_CLUSTER_NAME: litter-k8s-cluster
  AZURE_AKS_RESOURCE_GROUP: litter-k8s
  REGISTRY: ghcr.io

on:
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        type: choice
        required: true
        options:
          - "dev"
          - "staging"
          - "prod"

jobs:
  build-with-gradle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build (with tests)
        run: ./gradlew build

      # save the built JAR as artifact for building Docker image, ensure success
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/litter.jar
          if-no-files-found: error

  image-and-push:
    runs-on: ubuntu-latest
    environment: "Actions Environment"
    needs:
      - build-with-gradle
    permissions:
      contents: read
      packages: write
    outputs:
      image_path: ${{ steps.image-path.outputs.image_path }}
    timeout-minutes: 5

    steps:
      # checkout code for Dockerfile
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      # image repo must be lowercase and GitHub Actions makes this difficult
      # see: https://github.com/orgs/community/discussions/10553
      - name: Set image path (to lowercase)
        id: image-path
        run: |
          imagePath="${REGISTRY}/${GITHUB_REPOSITORY,,}"
          echo "image_path=$imagePath" >> $GITHUB_OUTPUT
          echo "Image path: $imagePath"

      # read version from gradle.properties and append to output so it can be used later
      - name: Read version from gradle.properties
        id: app-version
        run: |
          VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          if [ -z "$VERSION" ]; then
            echo "Error: Version not found in gradle.properties"; exit 1
          fi
          echo "app_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.image-path.outputs.image_path }}
          tags: |
            ${{ steps.app-version.outputs.app_version }}
            ${{ github.sha }}
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-azure:
    runs-on: ubuntu-latest
    environment: "Actions Environment"
    needs:
      - image-and-push
    permissions:
      actions: read
      contents: read
    timeout-minutes: 5

    steps:
      # checkout code for Helm chart
      - name: Git checkout
        uses: actions/checkout@v4

      # determine the deployment environment based on the trigger
      # if workflow is triggered by a pull request:
      #   ... and the base branch is 'main': staging
      #   ... otherwise: dev
      # if workflow is triggered by manual dispatch:
      #   ... use the environment input
      # the environment determines the Helm values file and the release name to use
      - name: Determine environment
        id: determine-env
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
              environment="staging" else environment="dev"
            fi
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            environment="${{ github.event.inputs.environment }}"
          else
            echo "Error: Unsupported event '${{ github.event_name }}'."
            exit 1
          fi
          
          echo "environment=$environment" >> $GITHUB_OUTPUT
          echo "values_file=values.${environment}.yaml" >> $GITHUB_OUTPUT
          echo "release_name=litter-${environment}" >> $GITHUB_OUTPUT
          echo "namespace=litter-${environment}" >> $GITHUB_OUTPUT

      - name: Azure login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get k8s context
        uses: Azure/aks-set-context@v4
        with:
          cluster-name: ${{ env.AZURE_AKS_CLUSTER_NAME }}
          resource-group: ${{ env.AZURE_AKS_RESOURCE_GROUP }}

      # merge values.yaml and the environment-specific values file
      - name: Merge Helm values with yq
        id: merge-values
        uses: mikefarah/yq@master
        with:
          cmd: |
            eval-all 'select(fileIndex == 0) * select(fileIndex == 1)'
            chart/values.common.yaml chart/${{ steps.determine-env.outputs.values_file }}
            > chart/merged.values.yaml

      # generate manifests using the merged values file
      - name: Generate manifests with Helm
        uses: Azure/k8s-bake@v3
        id: bake
        with:
          renderEngine: helm
          namespace: ${{ steps.determine-env.outputs.namespace }}
          releaseName: ${{ steps.determine-env.outputs.release_name }}
          helmChart: ./chart/
          overrideFiles: ./chart/merged.values.yaml
          overrides: |
            app.image.repository: ${{ needs.image-and-push.outputs.image_path }}
            app.image.tag: ${{ github.sha }}

      - name: Validate generated manifests
        uses: Azure/k8s-lint@v3
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}

      - name: Deploy app to AKS
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          namespace: ${{ steps.determine-env.outputs.namespace }}
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          imagepullsecrets: container-registry-secret